name: CI - build and test

on:                                
  push:
    branches: [ main, gh-pages ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Set up JDK 11
          uses: actions/setup-java@v3        
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew              
        - name: Build and test
          timeout-minutes: 20
          run: ./gradlew build
